"""Bake the Blockbench stand and its opening keyframes into dependency-free OBJ models.

Only the short opening uses the block entity renderer; resting models use the chunk mesh.
Run with --check to verify the generated resources without writing them.
"""
import argparse
import base64
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'src/main/resources/assets/forgermod'
SOURCE = ASSETS / 'models/block/ancient_sword_stand/ancient_sword_stand.bbmodel'
LAST_FRAME = 18


def rotate(point, pivot, angles):
    x,y,z = [point[i]-pivot[i] for i in range(3)]
    for axis, angle in enumerate(angles):
        c,s = math.cos(math.radians(angle)), math.sin(math.radians(angle))
        if axis == 0: y,z = y*c-z*s, y*s+z*c
        elif axis == 1: x,z = x*c+z*s, -x*s+z*c
        else: x,y = x*c-y*s, x*s+y*c
    return [x+pivot[0],y+pivot[1],z+pivot[2]]


def sample(animator, channel, time, default):
    keys = sorted((k for k in animator.get('keyframes', []) if k['channel'] == channel), key=lambda k:k['time'])
    if not keys: return default
    def value(key):
        if key['interpolation'] != 'linear': raise ValueError('Unsupported interpolation')
        return [float(key['data_points'][0][axis]) for axis in ('x','y','z')]
    if time <= keys[0]['time']: return value(keys[0])
    for a,b in zip(keys,keys[1:]):
        if time <= b['time']:
            t=(time-a['time'])/(b['time']-a['time'])
            return [x+(y-x)*t for x,y in zip(value(a),value(b))]
    return value(keys[-1])


def bake(source, animation, time):
    elements = {e['uuid']:e for e in source['elements']}
    groups = {g['uuid']:g for g in source['groups']}
    animators = animation['animators']
    texture = source['textures'][0]
    width,height = texture['uv_width'],texture['uv_height']
    lines=['# Generated by tools/export_ancient_stand.py',
           'mtllib forgermod:models/block/ancient_sword_stand/stand.mtl', 'usemtl stand']
    index=1
    def walk(nodes, parents):
        nonlocal index
        for node in nodes:
            if isinstance(node,dict):
                walk(node['children'], [groups[node['uuid']]]+parents)
                continue
            e=elements[node]
            if not e.get('export',True): continue
            if any(not any(sample(animators.get(g['uuid'],{}),'scale',time,[1,1,1])) for g in parents): continue
            x0,y0,z0=e['from']; x1,y1,z1=e['to']
            faces={
                'north':[(x1,y1,z0),(x1,y0,z0),(x0,y0,z0),(x0,y1,z0)],
                'south':[(x0,y1,z1),(x0,y0,z1),(x1,y0,z1),(x1,y1,z1)],
                'east':[(x1,y1,z1),(x1,y0,z1),(x1,y0,z0),(x1,y1,z0)],
                'west':[(x0,y1,z0),(x0,y0,z0),(x0,y0,z1),(x0,y1,z1)],
                'up':[(x0,y1,z0),(x0,y1,z1),(x1,y1,z1),(x1,y1,z0)],
                'down':[(x0,y0,z1),(x0,y0,z0),(x1,y0,z0),(x1,y0,z1)],
            }
            for name, vertices in faces.items():
                face=e['faces'][name]
                if face.get('texture') is None: continue
                a,b,c=vertices[:3]
                ab=[b[i]-a[i] for i in range(3)]; ac=[c[i]-a[i] for i in range(3)]
                if not any([ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]]): continue
                if face.get('rotation',0): raise ValueError('Unsupported face UV rotation')
                for vertex in vertices:
                    point=rotate(vertex,e.get('origin',[0,0,0]),e.get('rotation',[0,0,0]))
                    for group in parents:
                        animator=animators.get(group['uuid'],{})
                        pivot=group['origin']
                        scale=sample(animator,'scale',time,[1,1,1])
                        point=[pivot[i]+(point[i]-pivot[i])*scale[i] for i in range(3)]
                        angles=[a+b for a,b in zip(group.get('rotation',[0]*3),sample(animator,'rotation',time,[0]*3))]
                        point=rotate(point,pivot,angles)
                        point=[a+b for a,b in zip(point,sample(animator,'position',time,[0]*3))]
                    x,y,z=point
                    lines.append(f'v {(x+8)/16:.9f} {y/16:.9f} {(z+8)/16:.9f}')
                u0,v0,u1,v1=face['uv']
                for u,v in ((u0,v0),(u0,v1),(u1,v1),(u1,v0)):
                    lines.append(f'vt {u/width:.9f} {v/height:.9f}')
                lines.append('f '+' '.join(f'{i}/{i}' for i in range(index,index+4)))
                index+=4
    walk(source['outliner'],[])
    return ('\n'.join(lines)+'\n').encode()


def resources():
    source=json.loads(SOURCE.read_text(encoding='utf-8'))
    animations={a['name']:a for a in source['animations']}
    result={ASSETS/'textures/block/ancient_sword_stand/full_texture.png':base64.b64decode(source['textures'][0]['source'].split(',',1)[1]),
            ASSETS/'models/block/ancient_sword_stand/stand.mtl':b'newmtl stand\nKd 1 1 1\nd 1\nmap_Kd #stand\n'}
    def add_model(name,anim,time):
        mesh='block/ancient_sword_stand/'+name
        result[ASSETS/f'models/{mesh}.obj']=bake(source,animations[anim],time)
        data={'loader':'neoforge:obj','model':f'forgermod:models/{mesh}.obj','automatic_culling':False,
              'flip_v':False,'emissive_ambient':False,'render_type':'minecraft:cutout',
              'textures':{'stand':'forgermod:block/ancient_sword_stand/full_texture','particle':'forgermod:block/ancient_sword_stand/full_texture'}}
        result[ASSETS/f'models/{mesh}.json']=(json.dumps(data,indent=2)+'\n').encode()
    add_model('closed','Closed',0)
    add_model('open','Open',0)
    for i in range(LAST_FRAME+1): add_model('opening_'+str(i),'Opening',min(i/10,1.75))
    result[ASSETS/'models/block/ancient_sword_stand.json']=(json.dumps({'parent':'forgermod:block/ancient_sword_stand/closed','display':source['display']},indent=2)+'\n').encode()
    result[ASSETS/'models/block/ancient_sword_stand_empty.json']=b'{"parent": "forgermod:block/ancient_sword_stand/open"}\n'
    result[ASSETS/'models/block/ancient_sword_stand/opening.json']=b'{"textures": {"particle": "forgermod:block/ancient_sword_stand/full_texture"}}\n'
    variants={}
    for facing,angle in (('north',0),('east',90),('south',180),('west',270)):
        for full in (True,False):
            for opening in (True,False):
                model='ancient_sword_stand/opening' if opening else ('ancient_sword_stand' if full else 'ancient_sword_stand_empty')
                variants[f'facing={facing},full={str(full).lower()},opening={str(opening).lower()}']={'model':'forgermod:block/'+model,'y':angle}
    result[ASSETS/'blockstates/ancient_sword_stand.json']=(json.dumps({'variants':variants},indent=2)+'\n').encode()
    return result


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,content in resources().items():
        if args.check:
            if not path.exists() or path.read_bytes()!=content: raise SystemExit('Resource out of date: '+str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(content)
    print('Ancient stand resources verified.' if args.check else 'Ancient stand resources exported.')
