"""Export the supplied Blockbench Bedrock geometry to NeoForge's built-in OBJ loader.

Run from any directory with Python 3. No additional packages are required.
Use --check to verify that the checked-in resources match the source export.
"""

import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/main/resources/assets/forgermod"
SOURCE = ASSETS / "textures/item/Axe_void/Axe - Converted.geo.json"
VARIANTS = ("", "_ruby", "_amber", "_amethyst", "_jade")


def rotate(point, pivot, rotation):
    # Recover Blockbench's Java coordinate system from the mirrored Bedrock X axis.
    x, y, z = (point[i] - pivot[i] for i in range(3))
    for axis, angle in enumerate(rotation):
        c, s = math.cos(math.radians(angle)), math.sin(math.radians(angle))
        if axis == 0:
            y, z = y * c - z * s, y * s + z * c
        elif axis == 1:
            x, z = x * c + z * s, -x * s + z * c
        else:
            x, y = x * c - y * s, x * s + y * c
    return [x + pivot[0], y + pivot[1], z + pivot[2]]


def resources():
    geometry = json.loads(SOURCE.read_text(encoding="utf-8"))["minecraft:geometry"][0]
    width = geometry["description"]["texture_width"]
    height = geometry["description"]["texture_height"]
    lines = ["# Generated by tools/export_void_axe.py; edit the Blockbench source instead.",
             "mtllib axe_of_the_void.mtl", "usemtl axe"]
    index = 1
    for bone in geometry["bones"]:
        if any(bone.get("rotation", [])):
            raise ValueError("Bone rotations require hierarchical transforms before export")
        lines.append("g " + bone["name"])
        for cube in bone.get("cubes", []):
            ox, oy, oz = cube["origin"]
            sx, sy, sz = cube["size"]
            x0, x1, y0, y1, z0, z1 = -ox - sx, -ox, oy, oy + sy, oz, oz + sz
            pivot = cube.get("pivot", [0, 0, 0])
            pivot = [-pivot[0], pivot[1], pivot[2]]
            rotation = cube.get("rotation", [0, 0, 0])
            rotation = [-rotation[0], -rotation[1], rotation[2]]
            # Outward winding, ordered top-left, bottom-left, bottom-right, top-right.
            faces = {
                "north": [(x1, y1, z0), (x1, y0, z0), (x0, y0, z0), (x0, y1, z0)],
                "south": [(x0, y1, z1), (x0, y0, z1), (x1, y0, z1), (x1, y1, z1)],
                "east": [(x1, y1, z1), (x1, y0, z1), (x1, y0, z0), (x1, y1, z0)],
                "west": [(x0, y1, z0), (x0, y0, z0), (x0, y0, z1), (x0, y1, z1)],
                "up": [(x0, y1, z0), (x0, y1, z1), (x1, y1, z1), (x1, y1, z0)],
                "down": [(x0, y0, z1), (x0, y0, z0), (x1, y0, z0), (x1, y0, z1)],
            }
            for name, vertices in faces.items():
                # Flat decorative cubes retain their two visible faces; omit zero-area edges.
                a, b, c = vertices[:3]
                ab = [b[i] - a[i] for i in range(3)]
                ac = [c[i] - a[i] for i in range(3)]
                normal = [ab[1]*ac[2]-ab[2]*ac[1], ab[2]*ac[0]-ab[0]*ac[2],
                          ab[0]*ac[1]-ab[1]*ac[0]]
                if not any(normal):
                    continue
                face = cube["uv"][name]
                u, v = face["uv"]
                du, dv = face["uv_size"]
                # Bedrock top/bottom face UVs are reversed on both axes relative to Blockbench.
                if name in ("up", "down"):
                    u, v, du, dv = u + du, v + dv, -du, -dv
                uvs = [(u, v), (u, v + dv), (u + du, v + dv), (u + du, v)]
                for vertex in vertices:
                    x, y, z = rotate(vertex, pivot, rotation)
                    # OBJ units are blocks. Center the 42-unit axe for item display transforms.
                    lines.append(f"v {x/16+0.5:.9f} {(y-21)/16+0.5:.9f} {z/16+0.5:.9f}")
                for tu, tv in uvs:
                    lines.append(f"vt {tu/width:.9f} {tv/height:.9f}")
                lines.append("f " + " ".join(f"{i}/{i}" for i in range(index, index + 4)))
                index += 4
    display = {
        "thirdperson_righthand": {"rotation": [0, 90, 0], "translation": [0, 6, 1], "scale": [0.7]*3},
        "thirdperson_lefthand": {"rotation": [0, -90, 0], "translation": [0, 6, 1], "scale": [0.7]*3},
        "firstperson_righthand": {"rotation": [0, -90, 25], "translation": [0, 5, 0], "scale": [0.55]*3},
        "firstperson_lefthand": {"rotation": [0, 90, -25], "translation": [0, 5, 0], "scale": [0.55]*3},
        "gui": {"rotation": [0, 0, -35], "translation": [0, 0, 0], "scale": [0.32]*3},
        "ground": {"translation": [0, 2, 0], "scale": [0.25]*3},
        "fixed": {"rotation": [0, 180, 0], "scale": [0.32]*3},
        "head": {"translation": [0, 8, 0], "scale": [0.4]*3},
    }
    model = {
        "loader": "neoforge:obj",
        "model": "forgermod:models/item/axe_of_the_void.obj",
        "automatic_culling": False,
        "shade_quads": True,
        "flip_v": False,
        "emissive_ambient": False,
        "textures": {"axe": "forgermod:item/axe_of_the_void", "particle": "forgermod:item/axe_of_the_void"},
        "display": display,
    }
    result = {
        ASSETS / "models/item/axe_of_the_void.obj": ("\n".join(lines) + "\n").encode(),
        ASSETS / "models/item/axe_of_the_void.mtl": b"newmtl axe\nKd 1 1 1\nd 1\nmap_Kd #axe\n",
        ASSETS / "textures/item/axe_of_the_void.png": (SOURCE.parent / "axe_texture.png").read_bytes(),
    }
    for suffix in VARIANTS:
        data = model if not suffix else {"parent": "forgermod:item/axe_of_the_void"}
        result[ASSETS / f"models/item/axe_of_the_void{suffix}.json"] = (json.dumps(data, indent=2) + "\n").encode()
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in resources().items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"Resource out of date: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    print("Void axe resources verified." if args.check else "Void axe resources exported.")
